version: 1
buildpacks:
  - url: https://github.com/jontewks/puppeteer-heroku-buildpack
services:
  - type: web
    name: resume-builder-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
